In [1]:
import numpy as np
import pandas as pd

In [2]:
df = pd.read_csv('/home/mtv/Roopsingh/excel_file/titanic.csv')
df

PassengerId  Survived  Pclass  \
0              1         0       3   
1              2         1       1   
2              3         1       3   
3              4         1       1   
4              5         0       3   
..           ...       ...     ...   
886          887         0       2   
887          888         1       1   
888          889         0       3   
889          890         1       1   
890          891         0       3   

                                                  Name     Sex   Age  SibSp  \
0                              Braund, Mr. Owen Harris    male  22.0      1   
1    Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                               Heikkinen, Miss. Laina  female  26.0      0   
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                             Allen, Mr. William Henry    male  35.0      0   
..                                                 ...     ...   ...    ...   
886                              Montvila, Rev. Juozas    male  27.0      0   
887                       Graham, Miss. Margaret Edith  female  19.0      0   
888           Johnston, Miss. Catherine Helen "Carrie"  female   NaN      1   
889                              Behr, Mr. Karl Howell    male  26.0      0   
890                                Dooley, Mr. Patrick    male  32.0      0   

     Parch            Ticket     Fare Cabin Embarked  
0        0         A/5 21171   7.2500   NaN        S  
1        0          PC 17599  71.2833   C85        C  
2        0  STON/O2. 3101282   7.9250   NaN        S  
3        0            113803  53.1000  C123        S  
4        0            373450   8.0500   NaN        S  
..     ...               ...      ...   ...      ...  
886      0            211536  13.0000   NaN        S  
887      0            112053  30.0000   B42        S  
888      2        W./C. 6607  23.4500   NaN        S  
889      0            111369  30.0000  C148        C  
890      0            370376   7.7500   NaN        Q  

[891 rows x 12 columns]

In [3]:
new_df = df[['Pclass','Survived','Sex','Age','Fare']]

In [4]:
new_df

Pclass  Survived     Sex   Age     Fare
0         3         0    male  22.0   7.2500
1         1         1  female  38.0  71.2833
2         3         1  female  26.0   7.9250
3         1         1  female  35.0  53.1000
4         3         0    male  35.0   8.0500
..      ...       ...     ...   ...      ...
886       2         0    male  27.0  13.0000
887       1         1  female  19.0  30.0000
888       3         0  female   NaN  23.4500
889       1         1    male  26.0  30.0000
890       3         0    male  32.0   7.7500

[891 rows x 5 columns]

In [5]:
new_df.isna().sum()

Pclass        0
Survived      0
Sex           0
Age         177
Fare          0
dtype: int64

In [6]:
mean_age = new_df['Age'].mean()
new_df["Age"].fillna(mean_age,inplace=True)

/tmp/ipykernel_2686/3086890659.py:2: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_df["Age"].fillna(mean_age,inplace=True)


In [7]:
new_df.isna().sum()

Pclass      0
Survived    0
Sex         0
Age         0
Fare        0
dtype: int64

In [8]:
new_df.head()

Pclass  Survived     Sex   Age     Fare
0       3         0    male  22.0   7.2500
1       1         1  female  38.0  71.2833
2       3         1  female  26.0   7.9250
3       1         1  female  35.0  53.1000
4       3         0    male  35.0   8.0500

In [9]:
new_df['Pclass'].unique()

array([3, 1, 2])

In [10]:
new_df['Survived'].unique()

array([0, 1])

In [11]:
new_df['Sex'].unique()

array(['male', 'female'], dtype=object)

In [12]:
inputs = new_df.drop('Survived',axis=1)
target = new_df['Survived']

In [13]:
inputs.head()

Pclass     Sex   Age     Fare
0       3    male  22.0   7.2500
1       1  female  38.0  71.2833
2       3  female  26.0   7.9250
3       1  female  35.0  53.1000
4       3    male  35.0   8.0500

In [58]:
servived = new_df['Survived']
servived

0      0
1      1
2      1
3      1
4      0
      ..
886    0
887    1
888    0
889    1
890    0
Name: Survived, Length: 891, dtype: int64

In [15]:
from sklearn.preprocessing import LabelEncoder

In [16]:
le_sex = LabelEncoder()

In [17]:
inputs['Sex_n'] = le_sex.fit_transform(inputs['Sex'])

In [18]:
inputs.head()

Pclass     Sex   Age     Fare  Sex_n
0       3    male  22.0   7.2500      1
1       1  female  38.0  71.2833      0
2       3  female  26.0   7.9250      0
3       1  female  35.0  53.1000      0
4       3    male  35.0   8.0500      1

In [19]:
inputs.drop(['Sex'],axis=1,inplace=True)

In [45]:
new_df.head()

Pclass  Survived     Sex   Age     Fare
0       3         0    male  22.0   7.2500
1       1         1  female  38.0  71.2833
2       3         1  female  26.0   7.9250
3       1         1  female  35.0  53.1000
4       3         0    male  35.0   8.0500

In [28]:
inputs.head()

Pclass   Age     Fare  Sex_n
0       3  22.0   7.2500      1
1       1  38.0  71.2833      0
2       3  26.0   7.9250      0
3       1  35.0  53.1000      0
4       3  35.0   8.0500      1

In [63]:
new_df.head()

Pclass  Survived     Sex   Age     Fare
0       3         0    male  22.0   7.2500
1       1         1  female  38.0  71.2833
2       3         1  female  26.0   7.9250
3       1         1  female  35.0  53.1000
4       3         0    male  35.0   8.0500

In [62]:
merge = pd.concat([inputs,servived],axis=1)
merge

Pclass        Age     Fare  Sex_n  Survived
0         3  22.000000   7.2500      1         0
1         1  38.000000  71.2833      0         1
2         3  26.000000   7.9250      0         1
3         1  35.000000  53.1000      0         1
4         3  35.000000   8.0500      1         0
..      ...        ...      ...    ...       ...
886       2  27.000000  13.0000      1         0
887       1  19.000000  30.0000      0         1
888       3  29.699118  23.4500      0         0
889       1  26.000000  30.0000      1         1
890       3  32.000000   7.7500      1         0

[891 rows x 5 columns]

In [40]:
Pclass = np.array(inputs['Pclass']).reshape(-1,1)
Age = np.array(inputs['Age']).reshape(-1,1)
Fare = np.array(inputs['Fare']).reshape(-1,1)
Sex_n = np.array(inputs['Sex_n']).reshape(-1,1)
target = np.array(target).reshape(-1,1)


(891, 4)

In [23]:
from sklearn import tree

In [24]:
model = tree.DecisionTreeClassifier()

In [25]:
model.fit(inputs,target)

DecisionTreeClassifier()

In [42]:
model.score(inputs[['Pclass','Age','Fare','Sex_n']],new_df[['Survived']])

0.9797979797979798

In [44]:
model.predict([[3,22,7,1]])

/home/mtv/.local/lib/python3.8/site-packages/sklearn/base.py:464: UserWarning: X does not have valid feature names, but DecisionTreeClassifier was fitted with feature names
  warnings.warn(


array([0])

In [64]:
model.predict([[1,38,71,0]])

/home/mtv/.local/lib/python3.8/site-packages/sklearn/base.py:464: UserWarning: X does not have valid feature names, but DecisionTreeClassifier was fitted with feature names
  warnings.warn(


array([1])

In [66]:
model.predict([[1,19,30,0]])

/home/mtv/.local/lib/python3.8/site-packages/sklearn/base.py:464: UserWarning: X does not have valid feature names, but DecisionTreeClassifier was fitted with feature names
  warnings.warn(


array([1])