In [8]:
import numpy as np
import pandas as pd
from sklearn import linear_model
import matplotlib.pyplot as plt
import os

In [5]:
os.getcwd()

'/home/mtv/Roopsingh/jupyter_notebook'

In [6]:
df = pd.read_csv('/home/mtv/Roopsingh/excel_file/homeprices.csv')
df

area   price
0  2600  550000
1  3000  565000
2  3200  610000
3  3600  680000
4  4000  725000

In [16]:
area = np.array(df.area).reshape(-1,1)
price = np.array(df.price).reshape(-1,1)

In [17]:
model = linear_model.LinearRegression()
model.fit(area,price)

LinearRegression()

In [18]:
model.coef_

array([[135.78767123]])

In [19]:
model.intercept_

array([180616.43835616])

In [21]:
model.predict([[5000]])

array([[859554.79452055]])

In [22]:
import pickle

In [24]:
with open('model_pickle','wb') as f:
    pickle.dump(model,f)

In [25]:
with open('model_pickle','rb') as f:
    md = pickle.load(f)

In [28]:
md.predict([[6000]])

array([[995342.46575342]])

In [29]:
# Another way to save model

In [31]:
# from sklearn.externals import joblib
from joblib import dump, load

In [32]:
dump(model, 'model.joblib') 

['model.joblib']

In [33]:
m = load('model.joblib') 

In [34]:
m.predict([[6000]])

array([[995342.46575342]])