In [1]:
from sklearn.linear_model import LinearRegression
from sklearn.svm import SVC
from sklearn.ensemble import RandomForestClassifier
import numpy as np
from sklearn.datasets import load_digits
digits = load_digits()

In [10]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(digits.data,digits.target,test_size=0.3)

In [11]:
lr = LinearRegression()
lr.fit(X_train,y_train)
lr.score(X_test,y_test)

0.6020010221851908

In [12]:
svm = SVC()
svm.fit(X_train,y_train)
svm.score(X_test,y_test)

0.9888888888888889

In [13]:
rf = RandomForestClassifier()
rf.fit(X_train,y_train)
rf.score(X_test,y_test)

0.975925925925926

In [18]:
from sklearn.model_selection import KFold
kf = KFold(n_splits=3)
kf

KFold(n_splits=3, random_state=None, shuffle=False)

In [20]:
for train_index,test_index in kf.split([1,2,3,4,5,6,7,8,9]):
    print(train_index,test_index)

[3 4 5 6 7 8] [0 1 2]
[0 1 2 6 7 8] [3 4 5]
[0 1 2 3 4 5] [6 7 8]


In [23]:
def get_score(model,X_train,X_test,y_train,y_test):
    model.fit(X_train,y_train)
    return model.score(X_test,y_test)

In [24]:
get_score(LinearRegression(),X_train,X_test,y_train,y_test)

0.6020010221851908

In [25]:
get_score(SVC(),X_train,X_test,y_train,y_test)

0.9888888888888889

In [26]:
get_score(RandomForestClassifier(),X_train,X_test,y_train,y_test)

0.9814814814814815

In [27]:
from sklearn.model_selection import StratifiedKFold
fold = StratifiedKFold(n_splits=3)

In [31]:
score_l = []
score_svm = []
score_rf = []
for train_index,test_index in kf.split(digits.data):
    X_train,X_test,y_train,y_test = digits.data[train_index],digits.data[test_index],\
                                    digits.target[train_index],digits.target[test_index]
    score_l.append(get_score(LinearRegression(),X_train,X_test,y_train,y_test))
    score_svm.append(get_score(SVC(),X_train,X_test,y_train,y_test))
    score_rf.append(get_score(RandomForestClassifier(),X_train,X_test,y_train,y_test))

In [32]:
score_l

[0.5210503111571503, 0.5681424219493626, 0.41943985059688393]

In [33]:
score_svm

[0.9666110183639399, 0.9816360601001669, 0.9549248747913188]

In [34]:
score_rf

[0.9382303839732888, 0.9532554257095158, 0.9232053422370617]

In [35]:
from sklearn.model_selection import cross_val_score

In [37]:
cross_val_score(LinearRegression(),digits.data,digits.target)

array([0.48346048, 0.5583603 , 0.57534522, 0.5056632 , 0.40995457])

In [38]:
cross_val_score(SVC(),digits.data,digits.target)

array([0.96111111, 0.94444444, 0.98328691, 0.98885794, 0.93871866])

In [39]:
cross_val_score(RandomForestClassifier(),digits.data,digits.target)

array([0.93611111, 0.91666667, 0.95821727, 0.96657382, 0.93593315])